services:
  redis:
    container_name: ws-redis
    image: "redis:alpine"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"

  redis-insight:
    container_name: ws-redis-insight
    image: redis/redisinsight:latest
    restart: always
    ports:
      - "5540:5540"
    volumes:
      - redis-insight:/data

  localstack:
    container_name: ws-localstack
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - SERVICES=sqs
      - DEFAULT_REGION=us-east-1 
      - DEBUG=1
    volumes:
      - "./localstack_volume:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  db-data:
  redis-insight:
